### ISSUE TITLE
Issue about the COCO dataset

### ISSUE THREAD

**Issue by Sebastian-X** [Ze-Yang/Context-Transformer#1]
Hi, thanks for your work.
In 'split_coco_dataset_voc_nonvoc.py', you split 3 annotation files, but I can't find 'instances_valminusminival2014.json' and 'instances_minival2014.json' in the official website of COCO. Could you tell me where I can get these files?

**Comment by Endrhythm** [comment]
> Hi, thanks for your work.
> In 'split_coco_dataset_voc_nonvoc.py', you split 3 annotation files, but I can't find 'instances_valminusminival2014.json' and 'instances_minival2014.json' in the official website of COCO. Could you tell me where I can get these files?

- https://github.com/endernewton/tf-faster-rcnn/issues/293

**Comment by Ze-Yang** [comment]
You can download from [this link](http://images.cocodataset.org/annotations/annotations_trainval2014.zip).

**Comment by Sebastian-X** [comment]
Thanks for your reply!
I have another question about the prior boxes. In the original SSD, the output of its model includes prior box layers, which contain the coordinate information of all default boxes. In your code, however, these coordinates are computed out of the model. Instead, 'obj' is computed in the model, which is the output of a convolutional layer. What does this 'obj' part stand for? 
![WK((S)T$UPA)7 IFS4AH8H5](https://user-images.githubusercontent.com/58028948/79482482-7d34d500-8043-11ea-9c1d-d265b62adce2.png)

**Comment by Ze-Yang** [comment]
FYI, the prior box is the same as default boxes in SSD, as stated in Sec 4.1 in the our paper. Such boxes are predefined and don't require any update during training. Therefore, it's more efficient to compute it once out of the model, which is also applied in [RFBNet](https://github.com/ruinmessi/RFBNet).

As for the 'obj', it's a foreground/background classifier, somewhat like the objectness score (RPN output) in two-stage detector Faster RCNN. For details, please refer to Sec 3 of our paper. Thanks.

**Comment by Sebastian-X** [comment]
If I didn't get it wrong, this 'obj' part is the background classifier(BG) in your paper.

**Comment by Ze-Yang** [comment]
Exactly.

**Comment by Sebastian-X** [comment]
I see. Thanks for your help!
