### ISSUE TITLE
how to split voc data

### ISSUE THREAD

**Issue by Charles-kang** [Ze-Yang/Context-Transformer#3]
can you provide the python file of voc data split? 
thanks

**Comment by Ze-Yang** [comment]
- As for trainval_split*.txt used in VOC first phase training, we remove the annotations that belong to novel classes, and completely exclude an image when there is no annotation left. It's pretty easy to implement by yourself. Also free free to directly download the zip files we provide in the directory `data/` and place them according to the instructions in README.md.

- As for the trainval_*shot.txt that used for COCO to VOC setting, we just randomly pick image(s) that contains specific class annotation until it reaches designated shots. For instance, there will be 5 images (5-shot) selected for each class and all the annotations within these images will be used for finetuing.

Hope that it helps.

**Comment by Charles-kang** [comment]
thanks for your response, could you upload the .py file used to generate trainval_split*.txt used in VOC first phase training, I have re-implemented it, but there are some problems.
Thanks again!

**Comment by Ze-Yang** [comment]
Sorry for late reply. I have added a file named _split_voc_dataset.py_ under `data/` folder. Free free to run it by `python data/split_voc_dataset.py`. Hope it helps. Thanks.
