### ISSUE TITLE
How to train on a customized dataset?

### ISSUE THREAD

**Issue by duynn912** [Ze-Yang/Context-Transformer#7]
Hi @Ze-Yang,

I successfully re-produce your result with your readme. And I now want to train on my customized dataset which have the format similar to PASCAL. The dataset have 150 base classes and 50 novel classes. When I train base classes, it is ok. However, when transferring to novel classes, the loss is just nan!
![image](https://user-images.githubusercontent.com/39177680/86912087-8f0bad00-c146-11ea-9839-ac88880bd6f0.png)
I also change the classes in voc0712.py and some line in RFB_NET_vgg.py to be suitable to 150 base classes and 50 novel classes: 
![image](https://user-images.githubusercontent.com/39177680/86912156-ac407b80-c146-11ea-8bed-008e8aa45544.png)
So Could you help me out why it is in the case or there is any lines in some files that I have to change?

**Comment by Ze-Yang** [comment]
Nan loss may originate from various reasons, e.g., lr, initialization, etc. Our code does not support for customized dataset and you need to get around it by yourself. Thanks.
