### ISSUE TITLE
About Figure.5 in your paper

### ISSUE THREAD

**Issue by Sebastian-X** [Ze-Yang/Context-Transformer#8]
Hello!
I want to implement an Object Confusion experiment as your paper shows in Figure.5, but couldn't find an appropriate way. I tried to use  the number of True Positives(TP) and False Positives(FP) to represent (classification √ localization √) and (classification √ localization ×) respectively, but not sure if it makes sense and the results are far beyond from yours. Could you please briefly share experiment details about Figure.5, like what kind of metrics do you use. Thanks!
![BI(CVPNB(@VMXE% 2E{ RFJ](https://user-images.githubusercontent.com/58028948/88474923-af68a380-cf5d-11ea-9f6b-a185f78305ae.png)

**Comment by Ze-Yang** [comment]
Loc √ Cls √: correct label and IoU >= 0.5 with groundtruth box
Loc √ Cls ×: wrong label and IoU >= 0.5 with groundtruth box
Loc × Cls √: correct label and 0.3 <= IoU < 0.5 with groundtruth box
Loc × Cls ×: others

**Comment by Sebastian-X** [comment]
Normally, when we calculate AP of a category, only the detection boxes of this specific category are selected to compute IOU with groundtruth. However, your experiment contains 'correct label' and 'wrong label', does it mean all the detection boxes with different classification results are used for calculation?

**Comment by Ze-Yang** [comment]
Sure. We use all detection boxes for calculation.

**Comment by Sebastian-X** [comment]
Thanks for your help!
